# Generated by Django 5.2.16 on 2026-07-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_approved_at_event_approved_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_quantity", models.PositiveIntegerField()),
                ("remaining_quantity", models.PositiveIntegerField()),
                ("max_per_user", models.PositiveIntegerField(default=10)),
                ("sale_start", models.DateTimeField()),
                ("sale_end", models.DateTimeField()),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("color", models.CharField(default="blue", max_length=50)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "unique_together": {("event", "name")},
            },
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="ticket_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="events.tickettype",
            ),
        ),
    ]
