# Generated by Django 5.2.16 on 2026-07-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_tickettype_eventbooking_ticket_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="ticket_price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
