# Generated by Django 5.0.14 on 2026-08-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_end_time_eventschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
