# Generated by Django 5.2.15 on 2026-07-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_seed_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='online', max_length=50),
        ),
    ]
