# Generated by Django 5.2.16 on 2026-07-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_booking_approved_at_booking_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="venue_type",
            field=models.CharField(
                choices=[("indoor", "Indoor"), ("outdoor", "Outdoor")],
                db_index=True,
                default="outdoor",
                max_length=50,
            ),
        ),
    ]
