# Generated by Django 5.2.16 on 2026-07-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0004_venue_venue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
